import * as React from 'react';
import MaiComparisonModal from '.';

export default {
    title: 'Disclosure/MaiComparisonModal',
    component: MaiComparisonModal,
    tags: ['autodocs'],
    parameters: {
      docs: {
        description: {
          component: 'The <b>MaiComparisonModal</b> component displays a comparison modal highlighting the advantages of McDermott AI Chat over other AI tools.'
        },
      },
    },
};

export const Default = {
    decorators: [
        (Story: any) => (
            <div style={{ height: 800 }}>
                <Story />
            </div>
        ),
    ],
    args: {
        loading: false,
        isOpen: true,
        data: [
            {
                "FileSystemObjectType": 0,
                "Id": 1,
                "ServerRedirectedEmbedUri": null,
                "ServerRedirectedEmbedUrl": "",
                "ContentTypeId": "0x010048C10FE0E8D3E44DB13F27CDFD6B6282",
                "Title": "Work on a client or matter",
                "OData__ColorTag": null,
                "ComplianceAssetId": null,
                "ChatGPT": "No",
                "Copilot": "No",
                "McDermottAI": "Coming soon",
                "ID": 1,
                "Modified": "2026-01-14T19:12:46Z",
                "Created": "2026-01-14T19:11:50Z",
                "AuthorId": 18,
                "EditorId": 18,
                "OData__UIVersionString": "3.0",
                "Attachments": false,
                "GUID": "c6aedec5-7887-4e7b-a1be-9467a24d0b39"
            },
            {
                "FileSystemObjectType": 0,
                "Id": 2,
                "ServerRedirectedEmbedUri": null,
                "ServerRedirectedEmbedUrl": "",
                "ContentTypeId": "0x010048C10FE0E8D3E44DB13F27CDFD6B6282",
                "Title": "Review or analyze legal documents",
                "OData__ColorTag": null,
                "ComplianceAssetId": null,
                "ChatGPT": "No",
                "Copilot": "No",
                "McDermottAI": "Yes",
                "ID": 2,
                "Modified": "2026-01-14T19:12:45Z",
                "Created": "2026-01-14T19:12:01Z",
                "AuthorId": 18,
                "EditorId": 18,
                "OData__UIVersionString": "3.0",
                "Attachments": false,
                "GUID": "f5b90369-b67f-456f-b5b5-9b7c0c0d76c3"
            },
            {
                "FileSystemObjectType": 0,
                "Id": 3,
                "ServerRedirectedEmbedUri": null,
                "ServerRedirectedEmbedUrl": "",
                "ContentTypeId": "0x010048C10FE0E8D3E44DB13F27CDFD6B6282",
                "Title": "Summarize contracts or transcripts",
                "OData__ColorTag": null,
                "ComplianceAssetId": null,
                "ChatGPT": "No",
                "Copilot": "No",
                "McDermottAI": "Yes",
                "ID": 3,
                "Modified": "2026-01-14T19:12:44Z",
                "Created": "2026-01-14T19:12:14Z",
                "AuthorId": 18,
                "EditorId": 18,
                "OData__UIVersionString": "3.0",
                "Attachments": false,
                "GUID": "4ab173ec-ec4b-41b0-8e88-79b786200c59"
            },
            {
                "FileSystemObjectType": 0,
                "Id": 4,
                "ServerRedirectedEmbedUri": null,
                "ServerRedirectedEmbedUrl": "",
                "ContentTypeId": "0x010048C10FE0E8D3E44DB13F27CDFD6B6282",
                "Title": "Create firm work product",
                "OData__ColorTag": null,
                "ComplianceAssetId": null,
                "ChatGPT": "No",
                "Copilot": "No",
                "McDermottAI": "Yes",
                "ID": 4,
                "Modified": "2026-01-14T19:12:32Z",
                "Created": "2026-01-14T19:12:32Z",
                "AuthorId": 18,
                "EditorId": 18,
                "OData__UIVersionString": "1.0",
                "Attachments": false,
                "GUID": "0eef908d-a283-4125-9770-5959067ccba4"
            },
            {
                "FileSystemObjectType": 0,
                "Id": 5,
                "ServerRedirectedEmbedUri": null,
                "ServerRedirectedEmbedUrl": "",
                "ContentTypeId": "0x010048C10FE0E8D3E44DB13F27CDFD6B6282",
                "Title": "Support accuracy and defensibility",
                "OData__ColorTag": null,
                "ComplianceAssetId": null,
                "ChatGPT": "No",
                "Copilot": "No",
                "McDermottAI": "Yes",
                "ID": 5,
                "Modified": "2026-01-14T19:12:58Z",
                "Created": "2026-01-14T19:12:58Z",
                "AuthorId": 18,
                "EditorId": 18,
                "OData__UIVersionString": "1.0",
                "Attachments": false,
                "GUID": "ac502aac-93d3-42a3-8695-8604bfc3c3a8"
            },
            {
                "FileSystemObjectType": 0,
                "Id": 6,
                "ServerRedirectedEmbedUri": null,
                "ServerRedirectedEmbedUrl": "",
                "ContentTypeId": "0x010048C10FE0E8D3E44DB13F27CDFD6B6282",
                "Title": "Brainstorm ideas",
                "OData__ColorTag": null,
                "ComplianceAssetId": null,
                "ChatGPT": "Yes",
                "Copilot": "No",
                "McDermottAI": "Yes",
                "ID": 6,
                "Modified": "2026-01-14T19:13:36Z",
                "Created": "2026-01-14T19:13:36Z",
                "AuthorId": 18,
                "EditorId": 18,
                "OData__UIVersionString": "1.0",
                "Attachments": false,
                "GUID": "29b2df9a-53ee-499f-a154-0b0cd4d4aee1"
            },
            {
                "FileSystemObjectType": 0,
                "Id": 7,
                "ServerRedirectedEmbedUri": null,
                "ServerRedirectedEmbedUrl": "",
                "ContentTypeId": "0x010048C10FE0E8D3E44DB13F27CDFD6B6282",
                "Title": "Learn about a topic",
                "OData__ColorTag": null,
                "ComplianceAssetId": null,
                "ChatGPT": "Yes",
                "Copilot": "No",
                "McDermottAI": "Yes",
                "ID": 7,
                "Modified": "2026-01-14T19:14:58Z",
                "Created": "2026-01-14T19:14:58Z",
                "AuthorId": 18,
                "EditorId": 18,
                "OData__UIVersionString": "1.0",
                "Attachments": false,
                "GUID": "3fe0b718-5f18-4ab1-bf80-aa25a3e3052d"
            },
            {
                "FileSystemObjectType": 0,
                "Id": 8,
                "ServerRedirectedEmbedUri": null,
                "ServerRedirectedEmbedUrl": "",
                "ContentTypeId": "0x010048C10FE0E8D3E44DB13F27CDFD6B6282",
                "Title": "Draft non-client content",
                "OData__ColorTag": null,
                "ComplianceAssetId": null,
                "ChatGPT": "Yes",
                "Copilot": "Yes",
                "McDermottAI": "Yes",
                "ID": 8,
                "Modified": "2026-01-14T19:15:08Z",
                "Created": "2026-01-14T19:15:08Z",
                "AuthorId": 18,
                "EditorId": 18,
                "OData__UIVersionString": "1.0",
                "Attachments": false,
                "GUID": "23808042-3533-46b5-a4ca-115cd43170d5"
            },
            {
                "FileSystemObjectType": 0,
                "Id": 9,
                "ServerRedirectedEmbedUri": null,
                "ServerRedirectedEmbedUrl": "",
                "ContentTypeId": "0x010048C10FE0E8D3E44DB13F27CDFD6B6282",
                "Title": "Write or respond to emails",
                "OData__ColorTag": null,
                "ComplianceAssetId": null,
                "ChatGPT": "No",
                "Copilot": "Yes",
                "McDermottAI": "Yes",
                "ID": 9,
                "Modified": "2026-01-14T19:15:20Z",
                "Created": "2026-01-14T19:15:20Z",
                "AuthorId": 18,
                "EditorId": 18,
                "OData__UIVersionString": "1.0",
                "Attachments": false,
                "GUID": "d9fdbfc8-cd48-49d0-bb3e-543cf151cb2f"
            },
            {
                "FileSystemObjectType": 0,
                "Id": 10,
                "ServerRedirectedEmbedUri": null,
                "ServerRedirectedEmbedUrl": "",
                "ContentTypeId": "0x010048C10FE0E8D3E44DB13F27CDFD6B6282",
                "Title": "Work in Word, Excel, or PowerPoint",
                "OData__ColorTag": null,
                "ComplianceAssetId": null,
                "ChatGPT": "No",
                "Copilot": "Yes",
                "McDermottAI": "No",
                "ID": 10,
                "Modified": "2026-01-14T19:15:36Z",
                "Created": "2026-01-14T19:15:36Z",
                "AuthorId": 18,
                "EditorId": 18,
                "OData__UIVersionString": "1.0",
                "Attachments": false,
                "GUID": "046e0636-4fc1-49b4-999e-682774863df1"
            }
        ]
    },
};